### ISSUE TITLE
Detect system color mode on Firefox

### ISSUE THREAD

**Issue by TsotMe** [Eschricht/nuxt-color-mode#4]
It looks like there is a problem while detecting system color mode on Firefox.
It says that system color mode is light but it isn't.
You can test it on your provided playground, [here it is](https://stackblitz.com/github/Eschricht/nuxt-color-mode?file=playground%2Fapp.vue).

OS - Ubuntu 22.04.4
Firefox version - 128.0.3

**Comment by Eschricht** [comment]
I don't think `prefers-color-scheme` is passed to the iframe / app of the stackblitz example in Firefox. It should, however, work when running the example locally (it does for me). If not, maybe your firefox settings is blocking it somehow. Make sure that `privacy.resistfingerprinting` is set to `false`.

**Note:** Firefox does **not** yet support the `sec-ch-prefers-color-scheme` header so it will not be able to detect the preferred color scheme on server side. You can see the supported browsers [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-Prefers-Color-Scheme#browser_compatibility).
